#!/bin/bash
#
# Universal Workflow System - Subagent Generator (Milestone 1)
#
# Turns the 7 UWS personas (docs/personas/*.md + registry.yaml) into REAL
# Claude Code project subagents under .claude/agents/uws-<role>.md, so the
# orchestrator can dispatch work to isolated subagents via the Agent/Workflow
# tools instead of role-playing a single session.
#
# Idempotent: regenerates the files from the personas each run.
#
# Usage: ./scripts/gen_subagents.sh
#
# Per-role model (frontmatter `model:`; aliases per
# https://code.claude.com/docs/en/sub-agents: opus|sonnet|haiku|fable|inherit):
#   architect, researcher                         -> opus   (deep design/analysis)
#   implementer, experimenter, optimizer,
#   deployer, documenter                          -> sonnet
# Overrides (evaluated at generation time, highest precedence first):
#   UWS_AGENT_MODEL_<ROLE>=<alias>   e.g. UWS_AGENT_MODEL_IMPLEMENTER=opus
#   UWS_AGENT_MODEL=<alias>          all roles; UWS_AGENT_MODEL=inherit makes
#                                    every subagent use the session model
# An unknown alias is rejected (exit 1) before any file is written.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
PERSONA_DIR="${REPO_ROOT}/docs/personas"
AGENT_DIR="${REPO_ROOT}/.claude/agents"

GREEN='\033[0;32m'; CYAN='\033[0;36m'; RED='\033[0;31m'; NC='\033[0m'

ROLES=(researcher architect implementer experimenter optimizer deployer documenter)

role_description() {
    case "$1" in
        researcher)   echo "Requirements deep-dive, gap analysis, failure-mode inventory, and prior-art review. Use for UWS planning/requirements-phase research tasks." ;;
        architect)    echo "System and API design, data models, component diagrams, and cross-cutting concerns. Use for UWS design-phase tasks." ;;
        implementer)  echo "Production-grade code implementation with tests and zero stubs. Use for UWS implementation-phase coding tasks." ;;
        experimenter) echo "Verification, end-to-end testing, failure injection, and benchmarking. Use for UWS validation-phase tasks." ;;
        optimizer)    echo "Performance profiling and hypothesis-driven optimization with before/after evidence. Use for UWS optimization tasks." ;;
        deployer)     echo "Deployment, CI/CD, health checks, monitoring, and runbooks. Use for UWS delivery-phase tasks." ;;
        documenter)   echo "Documentation, guides, API docs, and tested examples. Use for UWS documentation tasks." ;;
        *)            echo "UWS ${1} agent." ;;
    esac
}

# Tools each subagent may use. Planning roles are read/write/search heavy;
# doers additionally need Bash. Kept permissive-but-scoped for autonomy.
role_tools() {
    case "$1" in
        researcher|architect|documenter) echo "Read, Grep, Glob, Write, Bash, WebSearch, WebFetch" ;;
        *)                               echo "Read, Grep, Glob, Write, Edit, Bash" ;;
    esac
}

VALID_MODELS="opus sonnet haiku fable inherit"

model_is_valid() {
    case " ${VALID_MODELS} " in
        *" $1 "*) return 0 ;;
        *)        return 1 ;;
    esac
}

role_upper() {
    printf '%s' "$1" | tr '[:lower:]' '[:upper:]'
}

# Default model per role; see header for rationale and overrides.
role_model_default() {
    case "$1" in
        architect|researcher) echo "opus" ;;
        *)                    echo "sonnet" ;;
    esac
}

# Resolve the model for a role: UWS_AGENT_MODEL_<ROLE> > UWS_AGENT_MODEL > default.
role_model() {
    local role="$1" var value
    var="UWS_AGENT_MODEL_$(role_upper "$role")"
    value="${!var:-}"
    [[ -z "$value" ]] && value="${UWS_AGENT_MODEL:-}"
    [[ -z "$value" ]] && value="$(role_model_default "$role")"
    if ! model_is_valid "$value"; then
        echo -e "${RED}Error: invalid model '${value}' for ${role} (valid: ${VALID_MODELS})${NC}" >&2
        return 1
    fi
    echo "$value"
}

# Resolve every model before writing anything, so a bad override leaves the
# existing agent files untouched.
for role in ${ROLES[@]+"${ROLES[@]}"}; do
    role_model "$role" >/dev/null || exit 1
done

if [[ ! -d "$PERSONA_DIR" ]]; then
    echo -e "${RED}Error: persona dir not found: ${PERSONA_DIR}${NC}" >&2
    exit 1
fi

mkdir -p "$AGENT_DIR"
protocol_file="${PERSONA_DIR}/_universal_protocol.md"

count=0
for role in ${ROLES[@]+"${ROLES[@]}"}; do
    persona_file="${PERSONA_DIR}/${role}.md"
    if [[ ! -f "$persona_file" ]]; then
        echo -e "${RED}skip ${role}: persona file missing${NC}" >&2
        continue
    fi

    out="${AGENT_DIR}/uws-${role}.md"
    desc="$(role_description "$role")"
    tools="$(role_tools "$role")"
    model="$(role_model "$role")"

    {
        echo "---"
        echo "name: uws-${role}"
        echo "description: ${desc}"
        echo "tools: ${tools}"
        echo "model: ${model}"
        echo "---"
        echo ""
        echo "<!-- AUTO-GENERATED by scripts/gen_subagents.sh from docs/personas/. Do not edit by hand. -->"
        echo "<!-- model: ${model}. To change it, re-run scripts/gen_subagents.sh with UWS_AGENT_MODEL_$(role_upper "$role")=<opus|sonnet|haiku|fable|inherit>, or UWS_AGENT_MODEL=inherit to use the session model for all roles. -->"
        echo ""
        if [[ -f "$protocol_file" ]]; then
            cat "$protocol_file"
            echo ""
        fi
        cat "$persona_file"
        echo ""
        cat << 'CONTRACT'
---

## Output Contract (UWS orchestration)

You are dispatched as an isolated subagent by the UWS orchestrator. Obey:

1. **Read your brief first**: `workspace/<role>/TASK.md` states the goal, current phase, the target output filename, and the deliverables checklist. If it is missing, stop and report.
2. **Write artifacts ONLY under `workspace/<role>/`**, mirroring the intended repo-relative path (the review pipeline diffs this directory).
3. **Trace every requirement/claim to a REQ-ID.** No unsourced assertions.
4. **Complete, not stubbed**: no TODOs, placeholders, or "implement later" markers in your artifact.
5. **Stay in your lane**: during planning-phase tasks (requirements/design) produce documents only — do NOT write application code.
6. **STOP at your persona Quality Gate.** Do not advance the workflow, create checkpoints, or mark deliverables yourself — the orchestrator and the human review gate own those.
CONTRACT
    } > "$out"

    echo -e "  ${GREEN}✓${NC} ${CYAN}.claude/agents/uws-${role}.md${NC} (model: ${model})"
    count=$(( count + 1 ))
done

echo -e "${GREEN}Generated ${count} subagent(s) in ${AGENT_DIR}${NC}"
